// src/lib/icebreakers.js
export const ICEBREAKERS = [
  "Share one professional and one personal win from the past 7 days.",
  "What's one thing you're grateful for this week?",
  "What's the best piece of advice you've ever received?",
  "What's a skill you've been wanting to learn?",
  "If you could have dinner with anyone in history, who would it be?",
  "What's your favorite way to recharge after a long day?",
  "What's one book that changed your perspective?",
  "What's something you're looking forward to this quarter?",
  "What's a recent challenge you overcame and what did you learn?",
  "What does your ideal weekend look like?",
  "What's the most interesting thing you've learned recently?",
  "If you could master any skill overnight, what would it be?",
  "What's one habit that's made a big difference in your life?",
  "What's your favorite local restaurant in Miami and why?",
  "What's a project or initiative you're most proud of at HHH?",
  "What song is currently stuck in your head?",
  "What's something most people don't know about you?",
  "What's your go-to productivity tip?",
  "If you could travel anywhere tomorrow, where would you go?",
  "What's a value that guides your work every day?",
  "What's one thing you'd change about your morning routine?",
  "What inspired you to work in your current role?",
  "What's the best team moment you've experienced at HHH?",
  "What's one word that describes your energy today?",
  "What's something you've changed your mind about recently?",
  "What's your favorite season and why?",
  "What's a cause or mission outside of work that you care about?",
  "What's one thing you do to stay creative?",
  "What's the last thing that made you laugh out loud?",
  "What's a podcast or show you'd recommend to the team?",
  "If HHH were a movie, what would the title be?",
  "What's one superpower you wish you had for work?",
  "What's your favorite part of Miami?",
  "What's a tradition you'd love to start at HHH?",
  "What's a goal you have outside of work this year?",
  "What motivates you most on a Monday morning?",
  "What's something from your childhood that still influences you?",
  "What's one small thing that makes your workday better?",
  "What's your go-to snack when you need energy?",
  "If you had an extra hour every day, what would you do with it?",
  "What's a fear you've overcome in your career?",
  "What does success look like to you personally?",
  "What's the most meaningful event you've worked on at HHH?",
  "What's a tool or app you can't live without?",
  "What's one thing you wish the team knew about your role?",
  "Who is a mentor or role model who shaped your career?",
  "What's the best feedback you've ever received?",
  "What's one way you like to recognize others' contributions?",
  "What surprised you most about working in the nonprofit sector?",
  "What's your spirit animal and why?",
  "What's a movie or show that reflects your personality?",
  "If you could redesign your workspace, what would it look like?",
  "What's one thing you want to accomplish before the end of the year?",
  "What's a recent win for HHH you want to celebrate?",
  "What's a skill you bring to the team that you're proud of?",
  "What's your favorite way to connect with the community?",
  "What's one question you'd ask a future version of yourself?",
  "What's something you do to stay grounded during stressful times?",
  "What's a fun fact about Miami most people don't know?",
  "What's a moment from your childhood that makes you smile?",
  "What's one thing you'd tell your younger professional self?",
  "What's the most impactful community event you've attended?",
  "What's a cultural tradition that's important to you?",
  "What's one thing you appreciate about this team?",
  "What's the best decision you made in the last 6 months?",
  "What's something on your bucket list?",
  "What's a value HHH has that resonates most with you?",
  "What's one way you've grown professionally this year?",
  "What's something HHH does that you're proud to be part of?",
  "What's a challenge the organization could tackle that excites you?",
  "What's your favorite way to celebrate a win?",
  "What's one thing you'd like to learn from someone on this team?",
  "What's something you do for fun that might surprise people?",
  "What's a word that describes how you want to show up this week?",
  "What's one area where you want to grow this quarter?",
  "What's something you're reading or watching right now?",
  "What's a moment when you felt most connected to HHH's mission?",
  "What's one thing you'd do if you knew you couldn't fail?",
  "What's your favorite Black history story or figure and why?",
  "What's one ritual that helps you start your day well?",
  "What's something you admire about someone on this team?",
  "What's a creative solution you've come up with recently?",
  "What's one thing you're currently learning outside of work?",
  "What's the most memorable conversation you've had this month?",
  "What's a small act of kindness you witnessed recently?",
  "What's your happiest work memory from this past year?",
  "What's one thing you want the team to know going into this meeting?",
  "What's a risk you're glad you took?",
  "What's something that energizes you about HHH's future?",
  "What's a lesson you learned the hard way?",
  "What's one thing you're doing to take care of yourself this week?",
  "What's a piece of music that moves you?",
  "What's something you're curious about right now?",
  "What's the best compliment you've ever received?",
  "What's one thing you want to achieve as a team this quarter?",
  "What's a moment you felt truly seen or appreciated at work?",
  "What's something that grounds you when things get hard?",
  "What's one way you contribute to the culture here?",
  "What's your definition of a great day at work?",
  "What's one thing about Miami that makes you proud?",
  "What's a hidden gem in Miami you'd recommend?",
];

export function getRandomIcebreaker(exclude) {
  const pool = exclude ? ICEBREAKERS.filter(q => q !== exclude) : ICEBREAKERS;
  return pool[Math.floor(Math.random() * pool.length)];
}
